Add documentation to twilio webhooks
mautic/mautic-documentation pull request #125
Opened 2020-09-18 20:30 UTC by mabumusa1

Explains the process of enabling webhooks from twilio to receive SMS and mark contacts as DNC

2020-09-19 18:11 UTC, RCheesley requested changes
Thanks for adding this information to the docs @mabumusa1 - a few typos and some suggestions to consider :)

2020-09-19 18:11 UTC, RCheesley commented on pages/07.Channels/01.Marketing Messages/03.SMS/docs.en.md
> +Contacts can unsubscribe from your SMS messags by replying with the word "Stop" to your SMS, Once Mautic recive this SMS that specific contact will be marked as Do not Contact and will not be contact
A couple of typos, and I believe the DNC is set per-channel so we should be clear that they will not be contacted by SMS but may still continue to be contacted via other channels (that is my understanding of how it works, at least).

```suggestion
Contacts can unsubscribe from your SMS messages by replying with the word "Stop" to your SMS. Once Mautic receives this SMS, that specific contact will be marked as Do Not Contact (DNC) and will not be contacted by SMS again.
```

2020-09-19 18:11 UTC, RCheesley commented on pages/07.Channels/01.Marketing Messages/03.SMS/docs.en.md
> +![](contact-reply.png)
```suggestion
![Screenshot of contact reply in their timeline](contact-reply.png)
```

2020-09-19 18:11 UTC, RCheesley commented on pages/07.Channels/01.Marketing Messages/03.SMS/docs.en.md
> +In order to make twilio send back the replies to Mautic you have to do the following steps:
```suggestion
In order to make Twilio send back the replies to Mautic, you have to take the following steps: 
```

2020-09-19 18:11 UTC, RCheesley commented on pages/07.Channels/01.Marketing Messages/03.SMS/docs.en.md
> +1. Go to twilio dashboard -> Phone Numbers -> Manage Numbers -> Active Numbers, then select the number you are sending from (the same number you configured in the steps above). or simple follow this
```suggestion
1. Go to the Twilio dashboard -> Phone Numbers -> Manage Numbers -> Active Numbers, then select the number you are sending from (the same number you configured in the steps above) or follow [this link][twilio-active-numbers]
```

2020-09-19 18:11 UTC, RCheesley commented on pages/07.Channels/01.Marketing Messages/03.SMS/docs.en.md
> +2. Go the messaging section, configure with webhook as shown in the screenshot below. make sure you point back to your server like this `https://domain.com/sms/twilio/callback`
```suggestion
2. Go the messaging section, configure with a webhook as shown in the screenshot below. Make sure you point back to your server like this `https://example.com/mautic/sms/twilio/callback` replacing example.com/mautic with the path to your Mautic instance.
```

2020-09-19 18:11 UTC, RCheesley commented on pages/07.Channels/01.Marketing Messages/03.SMS/docs.en.md
> +After these configurations you twilio will notify Mautic with any incoming SMS
```suggestion
After these configurations, Twilio will notify Mautic of any incoming SMS messages in response to your campaign.
```

2020-09-19 18:14 UTC, RCheesley requested changes
Sorry I messed up one of the file comments 😊

2020-09-19 18:14 UTC, RCheesley commented on pages/07.Channels/01.Marketing Messages/03.SMS/docs.en.md
> +![](twilio-webhook.png)
```suggestion
![Screenshot of Twilio webhook settings](twilio-webhook.png)
```

2020-09-19 18:14 UTC, RCheesley commented on pages/07.Channels/01.Marketing Messages/03.SMS/docs.en.md
> +After these configurations you twilio will notify Mautic with any incoming SMS
```suggestion
After these configurations, Twilio will notify Mautic of any incoming SMS messages in response to your campaign.```

2020-09-20 14:35 UTC, mabumusa1 reviewed
The changes look good to me, let's use them

2020-09-21 10:17 UTC, RCheesley approved these changes
LGTM! 🎉

2020-09-21 10:17 UTC, merged

2020-09-21 10:27 UTC, RCheesley commented
Looks like the changes were not enacted with a commit so I have just manually made them in the UI.