Added a disclaimer regarding rm -rf command
mautic/mautic-documentation pull request #127
Opened 2020-10-01 18:21 UTC by coderxx

A lot of people who jump to this section might end up deleting data without realising what they're doing. I feel it's proper to include a disclaimer.

2020-10-01 18:57 UTC, RCheesley requested changes
Good suggestion - I noticed an outdated reference to app/cache which I suggested we fix while we're here, and also think we should use the markup to create a warning box to make it visually stand out.

Thank you for taking the time to make the contribution!

2020-10-01 18:57 UTC, RCheesley commented on pages/03.Troubleshooting/docs.en.md
> +#### (Warning: Improper misuse of the 'rm -rf' command can delete entire folders and files from your project. Don't try it if you don't know what you're doing.)
Let's use the warning box markup to make it stand out

```suggestion
>>>> Warning: Improper misuse of the 'rm -rf' command can delete entire folders and files from your project. Don't try it if you don't know what you're doing.
```

2020-10-01 18:57 UTC, RCheesley commented on pages/03.Troubleshooting/docs.en.md
>  There are several ways to do that. The easiest is to go to the `/app/cache` folder and delete its content. If you want to do it via CLI command, navigate to the Mautic root folder and run `rm -rf app
Ooops, this is an old reference, let's update it while we are here!

```suggestion
There are several ways to do that. The easiest is to go to the `/var/cache` folder and delete its content. If you want to do it via CLI command, navigate to the Mautic root folder and run `rm -rf var/cache/*`. The new cache files will generate itself after the next Mautic refresh in the browser.
```

2020-10-02 04:27 UTC, coderxx reviewed
Updated the cache location. Didn't recognise this outdated reference. 
Changed message to warning

2020-10-02 04:40 UTC, coderxx reviewed
Fixed reference to cache folder

2020-10-04 07:40 UTC, coderxx reviewed
I think it looks good. No more changes that I can see.

2020-10-30 15:36 UTC, RCheesley approved these changes
🚀  LGTM sorry for the delay @coderxx !

2020-10-30 15:36 UTC, merged