add: always track utm tags
mautic/mautic-documentation pull request #128
Opened 2020-10-03 08:40 UTC by adiwegs

Add new text that all UTM tags from all requests are tracked. Keep a note for older versions.

2020-10-03 08:54 UTC, adiwegs commented
Related to https://github.com/mautic/mautic/pull/9265

2020-10-30 15:37 UTC, RCheesley approved these changes
Thanks for the update! Good to go once 3.2 is live!

2021-02-07 20:22 UTC, RCheesley requested changes
Updated to 3.3 and added the link per the [Styleguide](https://docs.mautic.org/en/home/contributing#linking-to-release-versions) ... now to get the PR merged!

2021-02-07 20:22 UTC, RCheesley commented on pages/09.contacts/01.manage-contacts/02.contact-monitoring/docs.en.md
> +Before version 3.2, UTM tags were only recorded on a form submission that contains the action "Record UTM Tags".
```suggestion
Before [Mautic 3.3][mautic-3.3], UTM tags were only recorded on a form submission that contains the action "Record UTM Tags".
```

2021-02-07 20:22 UTC, RCheesley commented on pages/09.contacts/01.manage-contacts/02.contact-monitoring/docs.en.md
> +Before version 3.2, UTM tags were only recorded on a form submission that contains the action "Record UTM Tags".
Please add the link macro at the bottom of the page: 

`[mautic-3.3]: <https://github.com/mautic/mautic/releases/tag/3.3>`

2021-08-31 20:35 UTC, RCheesley commented
@adiux a conflict to address before we can merge if you can please :) Thank you!

2021-12-08 08:59 UTC, adiux commented
closed in favor of https://github.com/mautic/mautic/pull/9265

2021-12-08 08:59 UTC, closed without merging