MaxMind ccpa
mautic/mautic-documentation pull request #151
Opened 2020-12-09 16:04 UTC by escopecz

Docs for https://github.com/mautic/mautic/pull/8647 and https://github.com/mautic/mautic/pull/8769

2021-02-07 19:52 UTC, RCheesley requested changes
A couple of recommendations - sorry for the delay in getting this merged!

2021-02-07 19:52 UTC, RCheesley commented on pages/02.Setup/03.Cron Jobs/docs.en.md
> +### MaxMind CCPA complience
```suggestion
### MaxMind CCPA compliance
```

2021-02-07 19:52 UTC, RCheesley commented on pages/02.Setup/03.Cron Jobs/docs.en.md
> +MaxMind requires to keep a "do not sell" list up to date and remove all data that were added by those IP addresses in the past from MaxMind.
```suggestion
MaxMind requires users to keep a "Do Not Sell" list up to date, and remove all data that was added relating to those IP addresses in the past from MaxMind.
```

2021-02-07 19:52 UTC, RCheesley commented on pages/02.Setup/03.Cron Jobs/docs.en.md
> +See more details in the official MaxMind website: https://blog.maxmind.com/tag/ccpa/
```suggestion
See more details in the official MaxMind website: [https://blog.maxmind.com/tag/ccpa/][maxmind-ccpa]
```

2021-02-07 19:52 UTC, RCheesley commented on pages/02.Setup/03.Cron Jobs/docs.en.md
> +See more details in the official MaxMind website: https://blog.maxmind.com/tag/ccpa/
Please add the link macro at the end of the page:

`[maxmind-ccpa]: <https://blog.maxmind.com/tag/ccpa/>`

2021-02-07 19:52 UTC, RCheesley commented on pages/02.Setup/03.Cron Jobs/docs.en.md
> +It's recommended to run those 2 commands once/week. One after another.
```suggestion
It is recommended to run these two commands once per week, one after another.
```

2021-02-07 19:52 UTC, RCheesley commented on pages/02.Setup/03.Cron Jobs/docs.en.md
> +This command will download the database of do not sell IP addresses from MaxMind.
```suggestion
This command will download the database of Do Not Sell IP addresses from MaxMind.
```

2021-02-07 19:52 UTC, RCheesley commented on pages/02.Setup/03.Cron Jobs/docs.en.md
> +This command will find data in the database that were loaded from MaxMind's do not sell IP addresses and deletes them.
```suggestion
This command will find data in the database that was loaded from MaxMind's Do Not Sell IP addresses and deletes the data.
```

2021-02-15 06:27 UTC, npracht approved these changes
👍🏽

2021-02-16 22:10 UTC, RCheesley approved these changes

2021-02-16 22:10 UTC, RCheesley commented on pages/02.Setup/03.Cron Jobs/docs.en.md
> +
```suggestion
```

2021-02-16 22:10 UTC, merged