Update Queue docs
mautic/mautic-documentation pull request #169
Opened 2021-02-07 19:16 UTC by fakela

2021-02-07 19:20 UTC, fakela commented
@RCheesley can you please tell me the syntax/configuration example that a user can use when trying to configure this in the local.php file.

also, i added info at the top to alert both old and new Mautic users of the change

2021-02-07 19:20 UTC, RCheesley requested changes

2021-02-07 19:20 UTC, RCheesley commented on pages/14.Queue/docs.en.md
> +> **_INfO:_**  Mautic 3.x users who are implementing RabbitMQ or Beanstalkd need to configure the settings directly in their local configuration file. If you are using the legacy Mautic 2.x series th
We can use the pretty styling here for a notes flash - they are documented in this PR: https://github.com/mautic/mautic-documentation/pull/162

```suggestion
> **_INFO:_**  Mautic 3.x users who are implementing RabbitMQ or Beanstalkd need to configure the settings directly in their local configuration file. If you are using the legacy Mautic 2.x series the steps below remains the same. 
```

2021-02-07 19:21 UTC, RCheesley commented on pages/14.Queue/docs.en.md
> +> **_INfO:_**  Mautic 3.x users who are implementing RabbitMQ or Beanstalkd need to configure the settings directly in their local configuration file. If you are using the legacy Mautic 2.x series th
Can we give an example of the syntax to use?

2021-07-13 17:30 UTC, RCheesley commented
@fakela I would suggest pinging the Product Team to ask for guidance on the syntax to be used - @mohit-rocks @npracht @jos0405 can you provide an example so we can get that documented?

2021-08-31 20:28 UTC, RCheesley commented
This PR needs to be updated with the latest changes, and have the configuration settings included. Please can you find someone to work on this @fakela ?

2021-09-06 01:56 UTC, fakela commented
This PR settles this https://github.com/mautic/mautic-documentation/pull/189 I will proceed to close this

2021-09-06 01:57 UTC, closed without merging