Improved accuracy and detail of pre-populating forms from a URL
mautic/mautic-documentation pull request #95
Opened 2020-07-29 15:11 UTC by gregharvey

I hope these are an improvement, they're accurate as far as I can tell from my testing.

2020-08-14 12:40 UTC, RCheesley requested changes
@gregharvey sorry I started a review ages ago and for some reason didn't post it!

I've made some suggestions for improvement as inline comments.

It might be helpful to reference the styleguide here: https://docs.mautic.org/en/home/contributing which has some guidelines on things like using links macros. We are trying to update these things as we go, so it would be super appreciated if you could look to pop any links in a block of macros at the bottom of the page.

Shout if you need any assistance!

2021-02-07 20:28 UTC, RCheesley commented
@gregharvey could you take a look at the proposed changes so we can get this merged?

2021-02-08 09:17 UTC, gregharvey commented on pages/10.Components/03.Forms/01.Managing Forms/docs.en.md
> +It is possible to pre-populate the value of a form field from the URL query parameters. However, this only works for form fields that are linked to contact fields, all of which can be found on the Se
"this is configured when you create the form" <- I did this ages ago, so I can't remember any more, but looking at my notes I'm not sure this is the case?

2021-02-08 10:09 UTC, gregharvey commented on pages/10.Components/03.Forms/01.Managing Forms/docs.en.md
Added the macro. You want the links to go to GitHub tags, I suppose?

2021-02-08 10:10 UTC, gregharvey commented
Sorry, I get so many GitHub notifications they're almost useless when it comes to spotting individual PRs needing a response! :-(

2021-02-09 15:38 UTC, RCheesley commented on pages/10.Components/03.Forms/01.Managing Forms/docs.en.md
Take a look at the docs here for linking to releases: https://docs.mautic.org/en/home/contributing#linking-to-release-versions

2021-02-09 15:39 UTC, RCheesley commented
No worries! Have replied to the last comment that is outstanding :)

2021-08-31 20:36 UTC, RCheesley commented
@gregharvey this one has a conflict to resolve now. Can you take a look please and also at the outstanding comments? Thanks!

2024-11-13 16:22 UTC, closed without merging